"""initial schema + pgvector extension + HNSW index

Revision ID: 0001_initial
Revises:
Create Date: 2026-06-25

This initial migration materializes the canonical SQLAlchemy schema, enables the
pgvector extension, and builds the HNSW index used for ANN retrieval. Subsequent
schema changes use reviewed autogenerated migrations (`alembic revision
--autogenerate`).
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from app.db.base import Base
import app.models  # noqa: F401  (populate Base.metadata)

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # Materialize all canonical tables from the model metadata.
    Base.metadata.create_all(bind=bind)

    if bind.dialect.name == "postgresql":
        # HNSW cosine index for fast ANN retrieval over episode embeddings.
        op.execute(
            "CREATE INDEX IF NOT EXISTS ix_episodes_embedding_hnsw "
            "ON diagnosis_episodes USING hnsw (embedding vector_cosine_ops)"
        )


def downgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("DROP INDEX IF EXISTS ix_episodes_embedding_hnsw")
    Base.metadata.drop_all(bind=bind)
